In [1]:
import numpy as np

In [111]:
m =  np.array([
[0,1,0,0,0,1],  # s0, the initial state, goes to s1 and s5 with equal probability
[4,0,0,3,2,0],  # s1 can become s0, s3, or s4, but with different probabilities
[0,0,0,0,0,0],  # s2 is terminal, and unreachable (never observed in practice)
[0,0,0,0,0,0],  # s3 is terminal
[0,0,0,0,0,0],  # s4 is terminal
[0,0,0,0,0,0],  # s5 is terminal 
    ])

In [87]:
def normalizeRows(a):
    row_sums = a.sum(axis=1) # array([ 9, 36, 63])
    new_matrix = np.zeros((6,6))
    for i, (row, row_sum) in enumerate(zip(a, row_sums)):
        new_matrix[i,:] = row / row_sum
    print new_matrix

In [88]:
normalizeRows(m)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


C:\Users\jhuan\Anaconda2\lib\site-packages\ipykernel\__main__.py:5: RuntimeWarning: divide by zero encountered in divide


In [134]:
def answer(m):
    for a in xrange(0, m.shape[0]):
        if m[a].sum() == 0:
            print a
            break
    T = m[:a, :]
    row_sums = np.sum(T, axis=1)
    T1 = np.empty([m.shape[0], 1])
    for b in xrange(0, a):
        T1 = np.append([T1], [T[b, :] / row_sums[b]], axis = 0)
        print T[b, :] / row_sums[b]
        print T
    print T1
    Q = m[:a, :a] 

In [135]:
answer(m)

2


ValueError: all the input arrays must have same number of dimensions